/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package typing.tutor;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Panel;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Tushar
 */
public class Tutorials extends javax.swing.JFrame {

    /**
     * Creates new form Tutorials
     */
    String path = "C:\\Users\\Tushar\\Neatbeans Projects\\Typing Tutor\\src\\typing\\tutor\\";
    int imageIndex = 0;
    int newYBound, yBound;
    WindowListener exitListener = new WindowAdapter() {

        @Override
        public void windowClosing(WindowEvent e) {
            exit();
        }
    };
    
    ImageIcon newIcon[] = new ImageIcon[5];
    
    public Tutorials() {
        Image backgroundImg = Toolkit.getDefaultToolkit().getImage(path + "background.jpg").getScaledInstance(760, 670, Image.SCALE_DEFAULT);
        ImageIcon image = new ImageIcon(backgroundImg);
        this.setContentPane(new JLabel(image));
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Tushar\\Neatbeans Projects\\Typing Tutor\\src\\typing\\tutor\\icon.png"));
        this.setTitle("Tutorials");

        initComponents();

        this.addWindowListener(exitListener);

        ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(path + "tutorial" + imageIndex + ".png"));
        Image img = icon.getImage().getScaledInstance(tutorialLabel.getWidth(), tutorialLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(img);
        tutorialLabel.setIcon(imageIcon);
        
        yBound = rButton1.getBounds().y;
        newYBound = rButton1.getBounds().y - 5;
        //rButton0.setBounds(rButton1.getBounds().x, newYBound, 15, 15);
        
        /*
        leftButton.setBackground(new Color(255,255,255,0));
        leftButton.setBounds(100, 100, 100, 100);
        //leftButton
        tutorialLabel.add(leftButton);
        */
        
        for(int i=0;i<5;i++){
            icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(path + "tutorial" + i + ".png"));
            img = icon.getImage().getScaledInstance(tutorialLabel.getWidth(), tutorialLabel.getHeight(), Image.SCALE_SMOOTH);
            newIcon[i] = new ImageIcon(img);
        }
        
    }

    public void exit() {
        new MainFrame().setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tutorialLabel = new javax.swing.JLabel();
        rButton0 = new javax.swing.JRadioButton();
        rButton1 = new javax.swing.JRadioButton();
        rButton2 = new javax.swing.JRadioButton();
        rButton3 = new javax.swing.JRadioButton();
        rButton4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(100, 20));
        setMaximumSize(new java.awt.Dimension(760, 670));
        setMinimumSize(new java.awt.Dimension(760, 670));
        setPreferredSize(new java.awt.Dimension(760, 670));
        setResizable(false);
        setSize(new java.awt.Dimension(760, 670));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TYPING GURU");

        tutorialLabel.setBackground(new java.awt.Color(0, 0, 0));
        tutorialLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tutorialLabel.setMaximumSize(new java.awt.Dimension(650, 620));
        tutorialLabel.setMinimumSize(new java.awt.Dimension(650, 620));
        tutorialLabel.setPreferredSize(new java.awt.Dimension(650, 620));
        tutorialLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorialLabelMouseClicked(evt);
            }
        });

        rButton0.setBackground(new java.awt.Color(0, 0, 255));
        rButton0.setSelected(true);
        rButton0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rButton0.setEnabled(false);
        rButton0.setFocusable(false);
        rButton0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rButton0.setMargin(new java.awt.Insets(1, 1, 1, 1));
        rButton0.setName(""); // NOI18N
        rButton0.setOpaque(false);

        rButton1.setBackground(new java.awt.Color(255, 255, 255));
        rButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rButton1.setEnabled(false);
        rButton1.setFocusable(false);
        rButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rButton1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        rButton1.setName(""); // NOI18N
        rButton1.setOpaque(false);

        rButton2.setBackground(new java.awt.Color(255, 51, 102));
        rButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rButton2.setEnabled(false);
        rButton2.setFocusable(false);
        rButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rButton2.setMargin(new java.awt.Insets(1, 1, 1, 1));
        rButton2.setName(""); // NOI18N
        rButton2.setOpaque(false);
        rButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButton2ActionPerformed(evt);
            }
        });

        rButton3.setBackground(new java.awt.Color(255, 51, 102));
        rButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rButton3.setEnabled(false);
        rButton3.setFocusable(false);
        rButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rButton3.setMargin(new java.awt.Insets(1, 1, 1, 1));
        rButton3.setName(""); // NOI18N
        rButton3.setOpaque(false);

        rButton4.setBackground(new java.awt.Color(255, 51, 102));
        rButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rButton4.setEnabled(false);
        rButton4.setFocusable(false);
        rButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rButton4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        rButton4.setName(""); // NOI18N
        rButton4.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tutorialLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rButton0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rButton4)
                .addGap(319, 319, 319))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tutorialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rButton0)
                    .addComponent(rButton1)
                    .addComponent(rButton2)
                    .addComponent(rButton3)
                    .addComponent(rButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutorialLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialLabelMouseClicked
        // TODO add your handling code here:
        if (evt.getX() > tutorialLabel.getWidth() / 2) {
            imageIndex = imageIndex >= 4 ? 4 : imageIndex + 1;
        }
        else if (evt.getX() <= tutorialLabel.getWidth() / 2) {
            imageIndex = imageIndex <= 0 ? 0 : imageIndex - 1;
        }
        renderImage();
    }//GEN-LAST:event_tutorialLabelMouseClicked

    
    private void rButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rButton2ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
        System.out.println(evt.getKeyCode());
        if (evt.getKeyCode() == 39) {
            imageIndex = imageIndex >= 4 ? 4 : imageIndex + 1;
        }
        else if (evt.getKeyCode() == 37) {
            imageIndex = imageIndex <= 0 ? 0 : imageIndex - 1;
        }
        renderImage();
    }//GEN-LAST:event_formKeyPressed

    void renderImage(){
        tutorialLabel.setIcon(newIcon[imageIndex]);

        if (imageIndex == 0) {
            rButton0.setSelected(true);
            rButton1.setSelected(false);

            //rButton0.setBounds(rButton0.getBounds().x, newYBound, 15, 15);
            //rButton1.setBounds(rButton1.getBounds().x, yBound, 15, 15);
        } else if (imageIndex == 1) {
            rButton0.setSelected(false);
            rButton1.setSelected(true);
            rButton2.setSelected(false);

            //rButton0.setBounds(rButton0.getBounds().x, yBound, 15, 15);
            //rButton1.setBounds(rButton1.getBounds().x, newYBound, 15, 15);
            //rButton2.setBounds(rButton2.getBounds().x, yBound, 15, 15);
        } else if (imageIndex == 2) {
            rButton1.setSelected(false);
            rButton2.setSelected(true);
            rButton3.setSelected(false);

            //rButton1.setBounds(rButton1.getBounds().x, yBound, 15, 15);
            //rButton2.setBounds(rButton2.getBounds().x, newYBound, 15, 15);
            //rButton3.setBounds(rButton3.getBounds().x, yBound, 15, 15);
        } else if (imageIndex == 3) {
            rButton2.setSelected(false);
            rButton3.setSelected(true);
            rButton4.setSelected(false);

            //rButton2.setBounds(rButton2.getBounds().x, yBound, 15, 15);
            //rButton3.setBounds(rButton3.getBounds().x, newYBound, 15, 15);
            //rButton4.setBounds(rButton4.getBounds().x, yBound, 15, 15);
        } else if (imageIndex == 4) {
            rButton3.setSelected(false);
            rButton4.setSelected(true);

            //rButton3.setBounds(rButton3.getBounds().x, yBound, 15, 15);
            //rButton4.setBounds(rButton4.getBounds().x, newYBound, 15, 15);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorials().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rButton0;
    private javax.swing.JRadioButton rButton1;
    private javax.swing.JRadioButton rButton2;
    private javax.swing.JRadioButton rButton3;
    private javax.swing.JRadioButton rButton4;
    private javax.swing.JLabel tutorialLabel;
    // End of variables declaration//GEN-END:variables
}
